### ISSUE TITLE
minor - "taxas_list" argument in vpr_roi_concentration()

### ISSUE THREAD

**Issue by kevinsorochan** [EOGrady21/vprr#41]
**Is your feature request related to a problem? Please describe.**
In the documentation, there is an argument "taxas_list". 

**Describe the solution you'd like**
The argument should be "taxa_list". "Taxas" does not make sense.

**Describe alternatives you've considered**
Ultimately, I think it would be preferable if, in all vprr functions, including vpr_roi_concentration(), "taxa" be replaced with "category". All classification categories are not necessarily taxonomic groups (e.g., marine_snow)

**Additional context**
NA

**Comment by EOGrady21** [comment]
Updated argument name in EC_functions and in relevant documentation (including vignette)
