### ISSUE TITLE
vpr_manual_classification() prompt

### ISSUE THREAD

**Issue by kevinsorochan** [EOGrady21/vprr#42]
**Describe the bug**
The prompt is not specific enough - it states that files will be deleted but not the directory or general location from which they will be deleted. Also there is a spelling error in the prompt.

**To Reproduce**
Reproducible code example of the bug, with output if appropriate.
```{r}

vpr_manual_classification

```

**Expected behavior**
The initial prompt should indicate some context regarding the files that will be removed and spelling should be correct 

Instead the function returns:

WARNING!!! ALL EXISITING FILES IN dXXX.hXX ARE ABOUT TO BE DELETED. DO YOU WISH TO PROCEED?

It should specify: ...all existing manual classification record files in dXXX.hXX are about to be deleted. Do you wish to proceed?

Note that EXISITING should be replaced with EXISTING 

**Screenshots**

NA
**Session Info:**
[output from running `sessionInfo()`]

**Additional context**

**Comment by EOGrady21** [comment]
I fixed the spelling error but left the original wording in the prompt, technically, the code written will delete ANY files stored in the dXX.hXXX folder... I wouldn't want any confusion or surprise on the off chance there were other files stored in the folder.
