### ISSUE TITLE
vpr_ctd_ymd documentation

### ISSUE THREAD

**Issue by kevinsorochan** [EOGrady21/vprr#66]
Suggest change to description of function in documentation:

Current description:

Calculate and record calendar dates for vpr data from day-of-year, hour, and time (in milliseconds) info. Will also add 'time_hr' parameter if not already present.

Suggested description:

Obtain columns for date and time (i.e., column "ymdhms") and time in hours (i.e., column time_hr) for each row in VPR data frame by utilizing day-of-year, hour, and millisecond outputs from VPR data output.

**Comment by kevinsorochan** [comment]
The value description should also be changed 

Current text:

a VPR data frame with complete date/time information in a new row named 'ymdhms'

Suggested text:

A VPR data frame with columns for date and time (i.e., column 'ymdhms') and hour (i.e., column time_hr)

**Comment by EOGrady21** [comment]
This looks good to me, you are welcome to make these documentation changes directly on main. It should not interfere with any tests or functionality.
