### ISSUE TITLE
vpr_category_create - documentation

### ISSUE THREAD

**Issue by kevinsorochan** [EOGrady21/vprr#70]
I suggest that the description of the basepath argument match that in the documentation of vpr_autoid_create 

"base path to auto ID folder eg 'E:/autoID_EC_07032019/'"

**Comment by EOGrady21** [comment]
That makes sense to me, documentation changes are easy to update in the main branch. It does seem like it would be better to keep this as generic as possible, maybe following the same example as is given in the vignette? ('extdata/COR2019002/autoid')

**Comment by kevinsorochan** [comment]
I believe this is now resolved
